dagster-user-deployments:
  enabled: true
  deployments:
    - name: "magasin-primero-pipeline-k8s"
      image:
        # change this with the image you want to deploy
        repository: "merlos/magasin-primero-pipeline"
        tag: latest
        pullPolicy: Always
      dagsterApiGrpcArgs:
        - "--package-name"
        - "magasin_primero"
      port: 3030
      envSecrets:
        - name: magasin-primero-pipeline-secret
      includeConfigInLaunchedRuns:
        enabled: true